export type CategoryIconOption = {
  name: string
  label: string
  keywords: string[]
}

export const categoryIconOptions: CategoryIconOption[] = [
  { name: 'Activity', label: 'Activity', keywords: ['health', 'movement', 'energy'] },
  { name: 'AlarmClock', label: 'Alarm', keywords: ['time', 'wake', 'routine'] },
  { name: 'Apple', label: 'Apple', keywords: ['food', 'health', 'nutrition'] },
  { name: 'Bath', label: 'Bath', keywords: ['self care', 'home', 'clean'] },
  { name: 'Bed', label: 'Bed', keywords: ['sleep', 'rest', 'home'] },
  { name: 'Bike', label: 'Bike', keywords: ['sport', 'exercise', 'transport'] },
  { name: 'BookOpen', label: 'Book', keywords: ['read', 'study', 'learn'] },
  { name: 'Brain', label: 'Brain', keywords: ['mind', 'focus', 'learn'] },
  { name: 'Brush', label: 'Brush', keywords: ['clean', 'teeth', 'care'] },
  { name: 'CalendarCheck', label: 'Calendar', keywords: ['plan', 'schedule', 'check'] },
  { name: 'Camera', label: 'Camera', keywords: ['photo', 'creative', 'journal'] },
  { name: 'Car', label: 'Car', keywords: ['drive', 'transport', 'errands'] },
  { name: 'ChefHat', label: 'Cooking', keywords: ['cook', 'kitchen', 'meal'] },
  { name: 'Circle', label: 'Circle', keywords: ['simple', 'default'] },
  { name: 'ClipboardCheck', label: 'Checklist', keywords: ['tasks', 'work', 'done'] },
  { name: 'Coffee', label: 'Coffee', keywords: ['drink', 'morning', 'break'] },
  { name: 'Computer', label: 'Computer', keywords: ['work', 'coding', 'screen'] },
  { name: 'Dumbbell', label: 'Dumbbell', keywords: ['gym', 'training', 'strength'] },
  { name: 'Feather', label: 'Writing', keywords: ['write', 'journal', 'creative'] },
  { name: 'Flame', label: 'Flame', keywords: ['streak', 'energy', 'focus'] },
  { name: 'Flower2', label: 'Flower', keywords: ['garden', 'mindful', 'nature'] },
  { name: 'Footprints', label: 'Walk', keywords: ['walk', 'steps', 'movement'] },
  { name: 'Gamepad2', label: 'Game', keywords: ['play', 'hobby', 'fun'] },
  { name: 'GraduationCap', label: 'Study', keywords: ['school', 'learn', 'course'] },
  { name: 'Guitar', label: 'Guitar', keywords: ['music', 'practice', 'instrument'] },
  { name: 'Hammer', label: 'Build', keywords: ['repair', 'house', 'project'] },
  { name: 'HeartPulse', label: 'Health', keywords: ['wellness', 'heart', 'care'] },
  { name: 'House', label: 'House', keywords: ['home', 'chores', 'clean'] },
  { name: 'Languages', label: 'Language', keywords: ['learn', 'study', 'words'] },
  { name: 'Laptop', label: 'Laptop', keywords: ['work', 'study', 'coding'] },
  { name: 'Leaf', label: 'Leaf', keywords: ['nature', 'garden', 'calm'] },
  { name: 'ListChecks', label: 'Checks', keywords: ['tasks', 'todo', 'done'] },
  { name: 'Medal', label: 'Medal', keywords: ['goal', 'win', 'progress'] },
  { name: 'Mic', label: 'Mic', keywords: ['voice', 'sing', 'record'] },
  { name: 'Moon', label: 'Moon', keywords: ['sleep', 'night', 'rest'] },
  { name: 'Mountain', label: 'Mountain', keywords: ['outdoor', 'hike', 'goal'] },
  { name: 'Music', label: 'Music', keywords: ['song', 'practice', 'sound'] },
  { name: 'NotebookPen', label: 'Notebook', keywords: ['journal', 'write', 'notes'] },
  { name: 'Paintbrush', label: 'Paint', keywords: ['art', 'creative', 'draw'] },
  { name: 'Palette', label: 'Palette', keywords: ['art', 'creative', 'color'] },
  { name: 'PersonStanding', label: 'Stretch', keywords: ['stretch', 'body', 'posture'] },
  { name: 'Piano', label: 'Piano', keywords: ['music', 'practice', 'instrument'] },
  { name: 'Plane', label: 'Travel', keywords: ['trip', 'travel', 'plan'] },
  { name: 'Recycle', label: 'Recycle', keywords: ['clean', 'eco', 'home'] },
  { name: 'Salad', label: 'Salad', keywords: ['food', 'health', 'meal'] },
  { name: 'Scale', label: 'Scale', keywords: ['weight', 'health', 'measure'] },
  { name: 'ShowerHead', label: 'Shower', keywords: ['clean', 'care', 'morning'] },
  { name: 'Smile', label: 'Smile', keywords: ['mood', 'mindful', 'happy'] },
  { name: 'Sparkles', label: 'Sparkles', keywords: ['clean', 'energy', 'care'] },
  { name: 'Sprout', label: 'Sprout', keywords: ['growth', 'nature', 'habit'] },
  { name: 'Star', label: 'Star', keywords: ['favorite', 'goal', 'focus'] },
  { name: 'Sun', label: 'Sun', keywords: ['morning', 'outdoor', 'light'] },
  { name: 'Target', label: 'Target', keywords: ['goal', 'focus', 'aim'] },
  { name: 'Timer', label: 'Timer', keywords: ['time', 'focus', 'pomodoro'] },
  { name: 'TreePine', label: 'Tree', keywords: ['nature', 'outdoor', 'garden'] },
  { name: 'Trophy', label: 'Trophy', keywords: ['achievement', 'goal', 'win'] },
  { name: 'Utensils', label: 'Meal', keywords: ['food', 'kitchen', 'eat'] },
  { name: 'Wallet', label: 'Wallet', keywords: ['money', 'budget', 'finance'] },
  { name: 'WashingMachine', label: 'Laundry', keywords: ['home', 'clean', 'clothes'] },
  { name: 'Waves', label: 'Water', keywords: ['water', 'swim', 'drink'] },
]

export const defaultCategoryIcon = 'Circle'
